# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000

create_project -in_memory -part xc7z020clg484-1
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/2019H1400080H/Documents/Object_Distance_Measurement/Object_Distance_Measurement.cache/wt [current_project]
set_property parent.project_path /home/2019H1400080H/Documents/Object_Distance_Measurement/Object_Distance_Measurement.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part em.avnet.com:zed:part0:1.2 [current_project]
add_files -quiet /home/2019H1400080H/Documents/Object_Distance_Measurement/Object_Distance_Measurement.runs/vio_0_synth_1/vio_0.dcp
set_property used_in_implementation false [get_files /home/2019H1400080H/Documents/Object_Distance_Measurement/Object_Distance_Measurement.runs/vio_0_synth_1/vio_0.dcp]
read_verilog -library xil_defaultlib {
  /home/2019H1400080H/Documents/Object_Distance_Measurement/Object_Distance_Measurement.srcs/sources_1/new/ultrasonic_sensor.v
  /home/2019H1400080H/Documents/Object_Distance_Measurement/Object_Distance_Measurement.srcs/sources_1/new/servo_motor.v
  /home/2019H1400080H/Documents/Object_Distance_Measurement/Object_Distance_Measurement.srcs/sources_1/new/Main_module.v
}
read_xdc /home/2019H1400080H/Documents/Object_Distance_Measurement/Object_Distance_Measurement.srcs/constrs_1/new/Obj_distance_measurement.xdc
set_property used_in_implementation false [get_files /home/2019H1400080H/Documents/Object_Distance_Measurement/Object_Distance_Measurement.srcs/constrs_1/new/Obj_distance_measurement.xdc]

catch { write_hwdef -file Main_module.hwdef }
synth_design -top Main_module -part xc7z020clg484-1
write_checkpoint -noxdef Main_module.dcp
catch { report_utilization -file Main_module_utilization_synth.rpt -pb Main_module_utilization_synth.pb }
